# docker-compose.yml
version: "3.8"
services:
  web:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - MODULE_NAME=main
